
#ifndef WEBSOCKETNETWORKING_LOCATIONCOORDINATES_H
#define WEBSOCKETNETWORKING_LOCATIONCOORDINATES_H

struct LocationCoordinates
{
    int area;
    int room;
};

#endif //WEBSOCKETNETWORKING_LOCATIONCOORDINATES_H
